name: Test Dockcheck Action

on:
  push:
    branches:
      - main
      
jobs:
  test-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test Docker Build Check
        uses: waanlabs/dockercheck@main
        with:
          path: .devcontainer/Dockerfile
          build_args: "--no-cache"
