name: Test Dockcheck Action with Security Scan

on:
  push:
    branches:
      - main
      
jobs:
  test-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test Docker Build and Security Scan
        uses: waanlabs/dockercheck@main
        with:
          path: ./.devcontainer  # Point to the directory containing the Dockerfile
          build_args: "--no-cache"
